fun main(args: Array<String>) {



    try {
        throw Exception()



    } catch (e: Exception) {
        println("aaa")
    }

}
